# Site settings
name: 叶小飞的博客
email: 283527215@qq.com
author: 叶小飞
url: 
resume_site:
github: https://github.com/yexiaofei-CN
baseurl: 
description: 叶小飞的博客！
meta_description: ...
motto: ...
banner: ...

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: yexiaofei-CN

# Build settings
markdown: kramdown

baidu_analysis: ''

